# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KP250Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('p4_link', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PlinkVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('p4_link', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='powermaxversion',
            name='p4_kp_250',
        ),
        migrations.RemoveField(
            model_name='powermaxversion',
            name='p4_plink',
        ),
        migrations.RemoveField(
            model_name='powermaxversion',
            name='plink_ver',
        ),
        migrations.AlterField(
            model_name='powermaxversion',
            name='kp_250',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.KP250Version'),
        ),
        migrations.AlterField(
            model_name='powermaxversion',
            name='p4_default',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='powermaxversion',
            name='p4_release',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='powermaxversion',
            name='plink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.PlinkVersion'),
        ),
    ]
