# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170621_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kp250version',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='plinkversion',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
