# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-22 19:39
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170621_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kp250version',
            name='p4_link',
            field=models.CharField(max_length=255, validators=[dashboard.models.p4_validator]),
        ),
        migrations.AlterField(
            model_name='plinkversion',
            name='p4_link',
            field=models.CharField(max_length=255, validators=[dashboard.models.p4_validator]),
        ),
        migrations.AlterField(
            model_name='powermaxversion',
            name='p4_default',
            field=models.CharField(max_length=255, validators=[dashboard.models.p4_validator]),
        ),
        migrations.AlterField(
            model_name='powermaxversion',
            name='p4_release',
            field=models.CharField(max_length=255, validators=[dashboard.models.p4_validator]),
        ),
        migrations.AlterField(
            model_name='powermaxversion',
            name='plink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.PlinkVersion'),
        ),
    ]
