# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170622_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powermaxversion',
            name='kp_250',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.KP250Version'),
        ),
    ]
