# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-20 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerMaxVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_type', models.CharField(max_length=30)),
                ('release', models.CharField(max_length=30)),
                ('default', models.CharField(max_length=30)),
                ('vlm', models.CharField(max_length=10)),
                ('eeprom_ver', models.CharField(default='Unknown', max_length=30)),
                ('plink_ver', models.CharField(blank='No Plink', max_length=30)),
                ('kp_250', models.CharField(default='Not supported', max_length=30)),
                ('comment', models.TextField(max_length=1000)),
                ('p4_release', models.URLField()),
                ('p4_default', models.URLField()),
                ('p4_plink', models.URLField(default='No Plink')),
                ('p4_kp_250', models.URLField(default='No KP250')),
            ],
        ),
    ]
