# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170622_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='powermaxversion',
            name='panel_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.PanelVersion'),
            preserve_default=False,
        ),
    ]
